### ISSUE TITLE
Error when running yarn build:production

### ISSUE THREAD

**Issue by jacobvd0** [HM4Development/mcpaste-addon#3]
Hey I get the following error when running yarn build:production:

root@panelvps:/var/www/pterodactyl# yarn build:production
yarn run v1.22.10
$ yarn run clean && cross-env NODE_ENV=production ./node_modules/.bin/webpack --mode production
$ cd public/assets && find . \( -name "*.js" -o -name "*.map" \) -type f -delete
/var/www/pterodactyl/node_modules/fs-extra/lib/mkdirs/make-dir.js:85
      } catch {
              ^

SyntaxError: Unexpected token {
    at NativeCompileCache._moduleCompile (/var/www/pterodactyl/node_modules/v8-compile-cache/v8-compile-cache.js:242:18)
    at Module._compile (/var/www/pterodactyl/node_modules/v8-compile-cache/v8-compile-cache.js:186:36)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (/var/www/pterodactyl/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/var/www/pterodactyl/node_modules/fs-extra/lib/mkdirs/index.js:3:44)
    at Module._compile (/var/www/pterodactyl/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (/var/www/pterodactyl/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/var/www/pterodactyl/node_modules/fs-extra/lib/copy-sync/copy-sync.js:5:20)
    at Module._compile (/var/www/pterodactyl/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (/var/www/pterodactyl/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/var/www/pterodactyl/node_modules/fs-extra/lib/copy-sync/index.js:4:13)
    at Module._compile (/var/www/pterodactyl/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by Antony1060** [comment]
This doesn't seem to be a problem with the addon itself. Make sure you ran `yarn install`.
